---
- name: This is a Conjur Ansible integration demo
  hosts: localhost
  connection: local
  become: yes
  vars:
    test_password: "{{ lookup('cyberark.conjur.conjur_variable', 'conjur:variable:data/vault/bnl-ansible-safe/Database-MySQL-ansible-test-user/password') }}"
  tasks:
    - name: Lookup variable in Conjur
      debug:
        msg: "{{test_password }}"

