---
- name: This is a Conjur Ansible integration demo
  hosts: localhost
  connection: local
  become: yes
  vars:
    test_password: "{{ lookup('cyberark.conjur.conjur_variable', 'data/vault/bnl-ansible-safe/Operating System-UnixSSHKeys-10.2.3.4-root/password') }}"
  tasks:
    - name: Lookup variable in Conjur
      debug:
        msg: "{{test_password.split('\n')  }}"
